$A = \sigma(w^T X + b) = (a^{(0)}, a^{(1)}, ..., a^{(m-1)}, a^{(m)})$

$J = -\frac{1}{m}\sum_{i=1}^{m}y^{(i)}\log(a^{(i)})+(1-y^{(i)})\log(1-a^{(i)})$

$ \frac{\partial J}{\partial w} = \frac{1}{m}X(A-Y)^T$

$ \frac{\partial J}{\partial b} = \frac{1}{m} \sum_{i=1}^m (a^{(i)}-y^{(i)})$

In [1]:
import numpy as np

In [2]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]).T
print(X)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [3]:
Y = np.array([0, 1, 0])
print(Y)

[0 1 0]


In [4]:
def compute_sigmoid(X, w, b):
    z = np.dot(w.T, X) + b
    A = 1 / (1 + np.exp(-1 * z))
    return A

In [5]:
def compute_cost(X, Y, w, b):
    A = compute_sigmoid(X, w, b)
    m = Y.shape[0]
    J = (-1 / m) * (np.sum(Y * np.log(A) + (1 - Y) * np.log(1 - A), axis = 1))
    return J[0]

In [6]:
def compute_gradient(X, Y, w, b):
    A = compute_sigmoid(X, w, b)
    m = Y.shape[0]
    dw = (1 / m) * np.dot(X, (A - Y).T)
    db = (1 / m) * np.sum(A - Y, axis = 1)
    return dw, db

In [10]:
threshold = 0.7
learning_rate = 0.001
w = np.array([[1], [1], [1], [1]])
b = 1

loss = compute_cost(X, Y, w, b)
print(loss)
while loss >= threshold:
    dw, db = compute_gradient(X, Y, w, b)
    w = w - learning_rate * dw
    b = b - learning_rate * db
    loss = compute_cost(X, Y, w, b)
    print(loss)

inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
15.144805930160368
15.12902978892732
15.113253727011479
15.097477748255303
15.08170185668847
15.06592605653762
14.819101292043408
14.803325688225485
14.787550189765785
14.636619765733778
14.620844493553323
14.509175318650543
14.4190191114387
14.342470369213316
14.275312059257988
14.175765979879444
14.12487135854567
14.021642315565652
13.958167915299317
13.881620121278928
13.798956133588664
13.727497877723318
13.642511399485848
13.569454838096414
13.489996841370385
13.408654060971791
13.33310131599813
13.254076961002834
13.178217781215487
13.099958508475625
13.021991867622456
12.943874675834948
12.867330141915652
12.789155956686253
12.71171000645774
12.633481631095414
12.555695952100088
12.477863819582682
12.400571708222113
12.322517434602283
12.244942114423157
12.16711327810081
12.089249273218522
12.011526049934673
11.933758543339248
11.855996153247755

/home/wenbo/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
