In [2]:
import numpy as np

In [3]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print(X.shape)

(3, 4)


In [6]:
Y = np.array([[1], [2], [3]])

In [7]:
print(Y)

[[1]
 [2]
 [3]]


In [8]:
print(Y.shape)

(3, 1)


X * W = Y, W = [w1, w2, w3, w4]T

1 * w1 + 2 * w2 + 3 * w3 + 4 * w4 = 1

5 * w1 + 6 * w2 + 7 * w3 + 8 * w4 = 2

9 * w1 + 10 * w2 + 11 * w3 + 12 * w4 = 3

In [9]:
print(X.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [10]:
W = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))

In [11]:
print(W)

[[-1.  ]
 [ 0.5 ]
 [ 0.  ]
 [ 0.25]]


In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression().fit(X, Y)

In [14]:
W2 = model.coef_

In [15]:
print(W2)

[[0.0625 0.0625 0.0625 0.0625]]


In [24]:
# compare np.dot() and np.matmul() operations
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2], [3, 4], [5, 6]])

print(A)
print(B)

result1 = np.matmul(A, B)
result2 = np.dot(A, B)

print(result1)
print(result2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]]
[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [72]:
def compute_loss(X, Y, W):
    return (np.dot((np.dot(X, W) - Y).T, (np.dot(X, W) - Y))) * (1 / X.shape[0]) 

def compute_gradient(X, Y, W):
    return 2 * (np.dot(np.dot(X.T, X), W) - np.dot(X.T, Y))

In [74]:
threshold = 0.0001
epsilon = 0.00001
W3 = np.ones((4, 1), dtype = int)

loss = compute_loss(X, Y, W3)
while loss >= threshold:
    W3 = W3 - epsilon * compute_gradient(X, Y, W3)
    loss = compute_loss(X, Y, W3)

print("optimal weights: {0}".format(W3))

optimal weights: [[-0.04263137]
 [ 0.0279143 ]
 [ 0.09845998]
 [ 0.16900566]]
